MASON = "application/vnd.mason+json"
PATRON_PROFILE = "/profiles/patron-profile/"
BOOK_PROFILE = "/profiles/book-profile/"
LOAN_PROFILE = "/profiles/loan-profile/"
HOLD_PROFILE = "/profiles/hold-profile/"
ERROR_PROFILE = "/profiles/error-profile/"
LINK_RELATIONS_URL = "/inlibris/link-relations/"
APIARY_URL = "https://inlibris.docs.apiary.io/#reference"